podinfo:
  enabled: true
  git:
    repo: https://github.com/AustinAbro321/podinfo-bigbang
    branch: main
    path: chart
  flux: {}
  ingress:
    gateway: ""


# Network Policies
networkPolicies:
  enabled: false

# Update existing values
istiooperator:
  enabled: false
istio:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckoperator:
  enabled: false
logging:
  enabled: false
fluentbit:
  enabled: false

# Monitoring
monitoring:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false  